services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    # This ensures Docker runs your code from inside the 'backend' folder
    working_dir: /app/backend
    volumes:
      # Map root to /app so both DB and 'backend' folder are visible
      - .:/app
      - chroma_data:/app/chroma_db
    environment:
      - DB_PATH=${DB_PATH}
      - DATA_ROOT=${DATA_ROOT}
      - BACKEND_PORT=5001
    ports:
      - "5001:5001"
    networks:
      - app-network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
      
  frontend:
    build: ./frontend
    container_name: frontend
    env_file: .env  # This tells Docker to load your .env file
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chroma_data: